version: "3.8"

services:
  database:
    container_name: database
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data

  cache:
    container_name: cache
    image: redis
    restart: always
    command: ["redis-server", "--port", "6379", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - ./cache:/data

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/ssl:/etc/ssl/certs
      - static-html:/var/www/html

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - static-html:/var/www/html

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight
    restart: always
    depends_on:
      - cache
    ports:
      - 8001:8001

volumes:
  static-html:
