version: "3.8"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: cache
    ports:
      - 6379:6379

  client:
    build: ./client

volumes:
  database:
    driver: local
