version: "3.8"

services:
  database:
    container_name: database
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

  cache:
    container_name: cache
    image: redis
    restart: always
    command: ["redis-server", "--port", "6379", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - ./cache:/data

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001

volumes:
  database:
    driver: local
