version: "3.8"

services:
  client:
    container_name: client
    working_dir: /client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/client

  database:
    container_name: database
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  server:
    container_name: server
    image: node:18
    restart: always
    working_dir: /server
    command: sh -c "yarn && yarn start"
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./server:/server

volumes:
  database:
    driver: local
