version: "3.8"

services:
  database:
    container_name: database
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./volumes/database:/var/lib/postgresql/data

  cache:
    container_name: cache
    image: redis/redis-stack:6.2.6-rc1
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./volumes/cache:/data

  models:
    container_name: models
    restart: unless-stopped
    build:
      context: ./models
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    depends_on:
      - cache

  server:
    container_name: server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - database
      - models

  client:
    container_name: client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./volumes/caddy:/data
      - ./volumes/uploads:/uploads
    ports:
      - 80:80
      - 443:443
